### PR TITLE
Update api json

### PR DESCRIPTION
**Pull request by nbeteram**
This pr contains a complete version of the api.json file. It follows the code on development (April 23, 2022, 00:31).

### CODE REVIEW

**Review by KoenDesplenter — APPROVED** [review]
Great job, amazing effort!

**Review by BramDevlaminck — CHANGES_REQUESTED** [review]
what happened with the tests that they suddenly fail?

**Review by jay-tux — CHANGES_REQUESTED** [review]
--- Session key overhaul is on dev already (requires entire update) ---

**Review by jay-tux — APPROVED** [review]

**Review by BramDevlaminck — APPROVED** [review]
awesome work! 🚀

**Pull request merged**
