### PR TITLE
Fix osoc-filter bug

### LINKED ISSUE #554: osocs filter generated errors
**Describe the bug**
OsocFilter does not sanitize user input

**To Reproduce**
1. Go to osocs page
2. fill in the inputs a string not a number
3. See error in the backend terminal

**Expected behavior**
does not throw error

This can be solved in either frontend or backend

### PR DESCRIPTION
**Pull request by jay-tux**
Fixes #554 (the new behavior throws an HTTP 401 Invalid Request because the parameter's value is invalid).

Turns out we really needed some validation in the BE parsers. I also took the liberty to check some requests for their session key instead of just mindlessly trying to extract one. Please use your heads when writing code...

### CODE REVIEW

**Review by BramDevlaminck — CHANGES_REQUESTED** [review]
This fix works for me! Could we also do the same in the "students" filter? The year field also throws an error there when not really entering a year (let me know if you think it's better to not do this on this branch, in that case I'll aprove here)

**Comment by jay-tux** [comment]
> This fix works for me! Could we also do the same in the "students" filter? The year field also throws an error there when not really entering a year (let me know if you think it's better to not do this on this branch, in that case I'll approve here)

@BramDevlaminck If you check the parser for the students filter, it already has this. I'd taken the liberty of fixing a lot of those issues.

**Comment by BramDevlaminck** [comment]
> > This fix works for me! Could we also do the same in the "students" filter? The year field also throws an error there when not really entering a year (let me know if you think it's better to not do this on this branch, in that case I'll approve here)
> 
> @BramDevlaminck If you check the parser for the students filter, it already has this. I'd taken the liberty of fixing a lot of those issues.

My bad, there is however still something that goes wrong when doing this. My guess this is a frontend issue @Mouwrice?

**Review by HuanYu-Tan — APPROVED** [review]

**Review by BramDevlaminck — APPROVED** [review]
works!

**Pull request merged**
