### PR TITLE
feat: websockets for users is now complete

### PR DESCRIPTION
**Pull request by BramDevlaminck**
- update when creating/deleting osoc edition
- update when user year permission changes
- also fixed the project permissions for coaches

### CODE REVIEW

**Comment by Mouwrice** [comment]
Hide the `Add project` and project edit / delete buttons for non admins:
image

**Review by Mouwrice — APPROVED** [review]
Tip top

**Review by Jonathan-Vanbrabant — APPROVED** [review]
Nice work!

**Comment by Mouwrice** [comment]
Remove the z-index from the paginator as it was beneath other elements and thus unclickable.

**Pull request merged**
