### PR TITLE
fix: finish and polish the students page

### LINKED ISSUE #517: fix: finish and polish the students page
The students page is not entirely finished and has some bugs that need fixing. This is primarily frontend work but there are also some backend issues that need to be resolved.

***Frontend:***
- [x] Make it possible to deselect a student #509 
- [x] Update the `EvalutationBar` as evaluation data is changed
- [x] Evaluations of another person are shown in the student overview
- [x] Update evaluations when making an evaluation
- [x] Better integration of the final decision

***Backend:***

- [x] Fix suggestion types #515 
- [x] Fix student evalutations #516

### PR DESCRIPTION
**Pull request by Mouwrice**
Closes #517

### CODE REVIEW

**Comment by Mouwrice** [comment]
A small update on the students page. Items fade to white when partially overflowing
image

**Comment by Mouwrice** [comment]
And for the mobile design:
image

**Comment by Mouwrice** [comment]
Student cards with the final decision in the corner:
image

**Comment by Mouwrice** [comment]
The status filter should only filter on the final decision, can anyone quickly fix this? Doesn't seem like much of a hassle.

image

**Comment by BramDevlaminck** [comment]
> The status filter should only filter on the final decision, can anyone quickly fix this? Doesn't seem like much of a hassle.
> 
> image

I've resolved this!

**Comment by Mouwrice** [comment]
I found why the job application links were not working. The data is a list of strings and not a string and the `href` element was not set for the anchor elements.

**Comment by BramDevlaminck** [comment]
image
I've noticed that when the motivation type is just a plain string (not a url) it's still clickable. I don't know if we can easily fix this?
We make a difference between these things in the database but I'm not sure if this difference is also there in the backend and if this data is send in the response to the frontend.

**Comment by BramDevlaminck** [comment]
image
When the curriculum, motivation and portfolio field have multiple links the links are separately highlighted but there is no newline! We should add some kind of newline/vertical spacing between seperate links (or in motivation this can also partially be a plain text)

**Review by BramDevlaminck — CHANGES_REQUESTED** [review]
Awesome! I've left some separate notes of small things we should fix.

On another note: I'm not quite sold on the double-scrollbar thing when we are in "full screen mode" (aka no student overview is visible, in all the other use cases it's awesome!) but it's not awful, so I'm fine with it.

**Comment by Mouwrice** [comment]
> Awesome! I've left some separate notes of small things we should fix.
> 
> On another note: I'm not quite sold on the double-scrollbar thing when we are in "full screen mode" (aka no student overview is visible, in all the other use cases it's awesome!) but it's not awful, so I'm fine with it.

The double scrollbar is indeed not great but it's the easiest thing to do to make the filter "sticky".

**Comment by Mouwrice** [comment]
> image
> When the curriculum, motivation and portfolio field have multiple links the links are separately highlighted but there is no newline! We should add some kind of newline/vertical spacing between seperate links (or in motivation this can also partially be a plain text)

Solved!

**Comment by Mouwrice** [comment]
> I've noticed that when the motivation type is just a plain string (not a url) it's still clickable. I don't know if we can easily fix this? We make a difference between these things in the database but I'm not sure if this difference is also there in the backend and if this data is send in the response to the frontend.

I don't think there's any distinction made in the backend because the frontend just receives this:
image

It's all just a motivation url

**Comment by BramDevlaminck** [comment]
> > I've noticed that when the motivation type is just a plain string (not a url) it's still clickable. I don't know if we can easily fix this? We make a difference between these things in the database but I'm not sure if this difference is also there in the backend and if this data is send in the response to the frontend.
> 
> I don't think there's any distinction made in the backend because the frontend just receives this: image
> 
> It's all just a motivation url

in that case there is a mistake somewhere in the backend!

**Comment by HuanYu-Tan** [comment]
The problem still persist of not updating the suggestions
image

**Comment by HuanYu-Tan** [comment]
There is currently no way to set the email status of a student (will this be handled in the projects page?)

**Comment by Mouwrice** [comment]
> There is currently no way to set the email status of a student (will this be handled in the projects page?)

Miet had some sort of remark on the email status so we'll first have to ask her what it exactly is they want.

**Comment by Mouwrice** [comment]
> The problem still persist of not updating the suggestions image

That's really interesting. Works flawless on my end

**Review by HuanYu-Tan — APPROVED** [review]

**Review by BramDevlaminck — CHANGES_REQUESTED** [review]
image
The problem still exists that the non-clickable motivation is clickable (I've checked in the database if it is right in there, and it really is a `MOTIVATION_STRING` in the database)

**Comment by Mouwrice** [comment]
> the line that is clickable and that should NOT be clickable is `this is a test textform about motivation`

Oh, jup seems like the backend fix didn't actually fix the issue.
image
image

**Review by BramDevlaminck — APPROVED** [review]
Beautiful work! 🚀

**Pull request merged**
