### PR TITLE
Fixing big project issues

### PR DESCRIPTION
**Pull request by Jonathan-Vanbrabant**
This pr addresses the **first** and the **third** point in #669.
The **second** point requires changes in a route which means rewriting code and a lot of fixing so this will be done in another pr when there is time left.

#### Changes in this pr:
- the **osoc edition functionality** has been **removed** from the frontend: when creating a new project, it will be assigned to the **current osoc edition**.
- the regular **alert** has been **changed** to the fancier **pop-up**.

Also:
- **project delete**: backend + frontend
- #681

### CODE REVIEW

**Comment by Mouwrice** [comment]
I did some styling to the change and delete buttons and also made description text wrap:
image

**Comment by Mouwrice** [comment]
Also fixed positions not updating.

**Review by nbeteram — APPROVED** [review]
very nice

**Review by BramDevlaminck — APPROVED** [review]
works for me!

**Pull request merged**
