### PR TITLE
User settings

### PR DESCRIPTION
**Pull request by HuanYu-Tan**
The user can change their own settings here

### CODE REVIEW

**Comment by HuanYu-Tan** [comment]
The logic works only syling is needed

**Comment by Mouwrice** [comment]
The styling has been done. I notice that code duplication is starting to pile up. We should seperate more items in components / generic functions for milestone 3. The styling is very basic and further improvements will come in milestone 3. Think of error / success notifications...

image

*The typo in the screenshot has already been fixed*

**Review by Mouwrice — APPROVED** [review]
BREAKING!

Important the sessionprovider has been updated
https://github.com/SELab-2/OSOC-2/blob/ebc6069275496dcbd24a3bf0b1e81a4637864d49/frontend/contexts/sessionProvider.tsx#L8-L25

The `getSessionKey()` function has been replaced by `getSession()` function which returns an object of type `{sessionKey: string, isAdmin: boolean, isCoach: boolean}` to be used in useEffect calls.

**Review by nbeteram — APPROVED** [review]

**Comment by Jonathan-Vanbrabant** [comment]
I can't seem to change my name without changing my password. Do I have to change my password every time i want to change my name?

Also the error messages I got were a bit weird.

image

**Review by Jonathan-Vanbrabant — APPROVED** [review]
This works now!

**Review by Mouwrice — APPROVED** [review]

**Review by Mouwrice — APPROVED** [review]

**Pull request merged**
