### PR TITLE
Projects overview

### LINKED ISSUE #373: feat: Design and implement the `Projects Overview` page
Implement the entire `/project` frontend route. It reuses the students components.

image

We can split this up in 5 sub tasks:
- [x]  Add a form to make a new project
- [x] Reuse the student components #303 
- [x] List all projects
- [x] Filter all projects
- [ ] Make projects interact able / editable

### PR DESCRIPTION
**Pull request by Mouwrice**
Should solve everything in #373 and closes #373.

### CODE REVIEW

**Comment by Mouwrice** [comment]
Current overview looks like this:
image

The students page functionality remains the same.
image

**Comment by Mouwrice** [comment]
The project card header is as good as finished:

image

**Comment by Mouwrice** [comment]
The create project page:
image

image

**Comment by Mouwrice** [comment]
Mobile design:
image

**Comment by Mouwrice** [comment]
Projects page with filter:
image

**Review by nbeteram — APPROVED** [review]

**Review by BramDevlaminck — APPROVED** [review]
There are a few things I noticed but I'll note down these "problems" in an issue. This way we can merge this as "temporary" projects. Everything is functional but a few changes would make it even better.

**Pull request merged**
