### PR TITLE
Frontend paging

### PR DESCRIPTION
**Pull request by Mouwrice**
Implements frontend paging for:

- [x] Students
- [ ] ~~Projects~~
- [x] Osoc Editions
- [x] Users

### CODE REVIEW

**Comment by Mouwrice** [comment]
The paging for the manage users is done!
image
image

**Comment by Mouwrice** [comment]
Student paging is also done!!

image
image

**Comment by Mouwrice** [comment]
Not admins can no longer create new osoc editions!
image

**Comment by Mouwrice** [comment]
Osoc editions: Pending #602 
image

**Review by BramDevlaminck — CHANGES_REQUESTED** [review]
A few things I noticed:
the text leaks outside the buttons. This does not really matter that much to me but I'll post it here anyways:
image

BREAKING:
- when refreshing you get redirected to the /students page!!!
- when changing the status of an account (make admin, or make coach,...) it does not get updated in the screen of the other users! (the refresh is still happening but the update itself seems to have broken)

**Review by HuanYu-Tan — APPROVED** [review]

**Review by BramDevlaminck — CHANGES_REQUESTED** [review]
The pagination with websockets is not working as supposed (page always reset to page 0), I'll fix this tonight

**Review by BramDevlaminck — APPROVED** [review]
works as expected

**Pull request merged**
